### ISSUE TITLE
Incorrect attribute value type errors

### ISSUE THREAD

**Issue by MikeyUchiha** [gruntwork-io/terraform-google-gke#45]
https://github.com/gruntwork-io/terraform-google-gke/tree/master/examples/gke-private-tiller

After running terraform plan I get the following errors:

```
var.location
  The location (region or zone) of the GKE cluster.

  Enter a value: us-east4

var.project
  The project ID where all resources will be launched.

  Enter a value: be-my-player-two

var.region
  The region for the network. If the cluster is regional, this must be the same region. Otherwise, it should be the region of the zone.

  Enter a value: us-east4


Error: Incorrect attribute value type

  on modules\gke-cluster\main.tf line 51, in resource "google_container_cluster" "cluster":
  51:       disabled = "${var.http_load_balancing ? 0 : 1}"

Inappropriate value for attribute "disabled": bool required.


Error: Incorrect attribute value type

  on modules\gke-cluster\main.tf line 55, in resource "google_container_cluster" "cluster":
  55:       disabled = "${var.horizontal_pod_autoscaling ? 0 : 1}"

Inappropriate value for attribute "disabled": bool required.


Error: Incorrect attribute value type

  on modules\gke-cluster\main.tf line 59, in resource "google_container_cluster" "cluster":
  59:       disabled = "${var.enable_kubernetes_dashboard ? 0 : 1}"

Inappropriate value for attribute "disabled": bool required.


Error: Incorrect attribute value type

  on modules\gke-cluster\main.tf line 63, in resource "google_container_cluster" "cluster":
  63:       disabled = "${var.enable_network_policy ? 0 : 1}"

Inappropriate value for attribute "disabled": bool required.


Error: Unsupported argument

  on modules\gke-cluster\main.tf line 83, in resource "google_container_cluster" "cluster":
  83:   master_authorized_networks_config = "${var.master_authorized_networks_config}"

An argument named "master_authorized_networks_config" is not expected here.
Did you mean to define a block of type "master_authorized_networks_config"?
```

**Comment by MikeyUchiha** [comment]
https://github.com/hashicorp/terraform/issues/6254#issuecomment-390279669

I found this link from Terraform. Maybe this has something to do with the "bool required" issue?

**Comment by MikeyUchiha** [comment]
Also found this in the documentation that bool values only take true or false and not integers like 0 or 1.
https://www.terraform.io/docs/configuration/expressions.html#types-and-values

**Comment by yorinasub17** [comment]
Hi @MikeyUchiha , can you share which version of terraform you are using? Just so you are aware, we haven't updated this module to support tf 0.12+ yet, so if you are on that, that would explain the issue.

**Comment by MikeyUchiha** [comment]
Hi @yorinasub17 that is correct. I'm using tf 0.12 and what is the release timeline on support for it?
Thanks!

**Comment by MikeyUchiha** [comment]
Also, shouldn't the terraform required version reflect this?

```
terraform {
  required_version = ">= 0.10.3"
}
```

**Comment by MikeyUchiha** [comment]
@yorinasub17 I just wanted to follow up with my question. Do I need to update the required_version field?

**Comment by yorinasub17** [comment]
Hi @MikeyUchiha,

Sorry for the delay in getting back to you. We are in the process of upgrading all our modules to support tf12 (e.g we have PRs open for the other ones: [terraform-google-network](https://github.com/gruntwork-io/terraform-google-network/pull/26), [terraform-google-load-balancer](https://github.com/gruntwork-io/terraform-google-load-balancer/pull/8), [terraform-google-static-assets](https://github.com/gruntwork-io/terraform-google-static-assets/pull/9)). We don't have a clear timeline on the process, but we will likely get to this module before the end of the month. I don't think it is necessary to update the `required_version` field, since updating it won't help with the already released versions.

**Comment by MikeyUchiha** [comment]
@yorinasub17 Thank you very much for the thorough explanation. I will close out this issue and look forward to the update.

**Comment by yorinasub17** [comment]
Actually, let's keep this issue open until the update is merged.

**Comment by MikeyUchiha** [comment]
Ok. Thank you

**Comment by robmorgan** [comment]
Fixed in: https://github.com/gruntwork-io/terraform-google-gke/releases/tag/v0.3.0

**Comment by tjanson** [comment]
This is still broken in the `google-blog-post-oics` branch which is used in [the Google Cloud blog post](https://cloud.google.com/blog/products/devops-sre/deploying-a-production-grade-helm-release-on-gke-with-terraform), i.e., you can’t follow the tutorial.
